export const regionals = {
    "Farfetchd": 3,
    "Kangaskhan": 4,
    "Mr. Mime": 5,
    "Tauros": 6,

    "Heracross": 7,
    "Corsola": 17,

    "Volbeat": 1,
    "Illumise": 2,
    "Torkoal": 16,
    "Zangoose": 1,
    "Seviper": 2,
    "Lunatone": 1,
    "Solrock": 2,
    "Tropius": 15,
    "Relicanth": 18,

    "Pachirisu": 19,
    "Shellos": 12,
    "Mime Jr.": 5,
    "Chatot": 9,
    "Carnivine": 14,
    "Uxie": 13,
    "Mesprit": 8,
    "Azelf": 10,

    "Pansage": 13,
    "Pansear": 8,
    "Panpour": 10,
    "Throh": 2,
    "Sawk": 1,
    "Basculin": 12,
    "Maractus": 7,
    "Sigilyph": 11,
    "Heatmor": 2,
    "Durant": 1,
}