version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}
    bolt_data: {}
    log_data: {}
    letsencrypt: {}
    mongodb_data: {}
    mongodb_backups: {}

services:
mongo1:
    container_name: pogmongo
    image: mongo:latest
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
      - mongodb_backups:/backups
    restart: always
    labels:
        - "traefik.enable=false"
simulator:
    container_name: simulator
    volumes:
        - bolt_data:/app/boltDB
        - log_data:/app/logs/
    environment:
        - MONGO_URI=${MONGO_URI}
        - SECRET_CAPTCHA=${SECRET_CAPTCHA}
        - GMAIL_PASS=${GMAIL_PASS}
        - JWT_KEY=${JWT_KEY}
        - COOKIE_DOMAIN=${COOKIE_DOMAIN}
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simulator.rule=Host(`pogpvp.com`)"
      - "traefik.http.routers.simulator.entrypoints=websecure"
      - "traefik.http.routers.simulator.tls=true"
      - "traefik.http.routers.simulator.tls.certresolver=myresolver"
      - "traefik.port=8080"
    depends_on:
      - mongo1
prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prom.pogpvp.com`)"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
      - "traefik.port=9090"
      - "traefik.http.routers.prometheus.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${USR_PSWD}"
    volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - prometheus_data:/prometheus
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml" 
      - "--web.console.templates=/etc/prometheus/consoles" 
      - "--web.console.libraries=/etc/prometheus/console_libraries" 
      - "--storage.tsdb.path=/prometheus" 
      - "--storage.tsdb.retention=168h"
      - "--storage.tsdb.retention.size=2GB"
    restart: always
    deploy:
        resources:
          limits:
            cpus: '0.10'
            memory: 45M
    depends_on:
      - simulator
grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    #environment:
      #- GF_INSTALL_PLUGINS=https://github.com/raintank/crate-datasource/archive/master.zip;crate-datasource,grafana-clock-panel,grafana-worldmap-panel,natel-plotly-panel
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`graph.pogpvp.com`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.port=3000"
    restart: always
    volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/datasources:/etc/grafana/datasources
        - ./grafana/dashboards:/etc/grafana/dashboards
        - ./grafana/setup.sh:/setup.sh
    deploy:
        resources:
          limits:
            cpus: '0.10'
            memory: 50M
    depends_on:
      - prometheus
  traefik:
        image: "traefik:v2.2"
        container_name: "traefik"
        command:
          #- "--log.level=DEBUG"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
          #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
          - "--certificatesresolvers.myresolver.acme.email=blizzz93@gmail.com"
          - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
          - "80:80"
          - "443:443"
        labels:
         - "traefik.enable=true"
          #middleware compressor
         - "traefik.http.middlewares.test-compress.compress=true"
         # middleware redirect  
         - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"  
         # global redirect to https  
         - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"  
         - "traefik.http.routers.http-catchall.entrypoints=web"
         - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"  
        volumes:
          - "letsencrypt:/letsencrypt/"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        logging:
          options:
              max-size: '25m'
              max-file: '3'
        depends_on:
            - grafana
