global:
  scrape_interval:     60s 
  evaluation_interval: 60s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'simulator'
    static_configs:
      - targets: ['simulator:8181']
